# Generated by Django 6.0 on 2025-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(max_length=18, unique=True, verbose_name='Cartão Nacional de Saúde (CNS)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
