# Generated by Django 6.0 on 2026-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(error_messages={'unique': 'Já existe um paciente cadastrado com este CNS.'}, max_length=18, unique=True, verbose_name='Cartão Nacional de Saúde (CNS)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Já existe um paciente cadastrado com este CPF.'}, max_length=14, null=True, unique=True),
        ),
    ]
