# Generated by Django 6.0 on 2026-01-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(max_length=15, unique=True, verbose_name='Cartão Nacional de Saúde (CNS)')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Ignorado')], max_length=1)),
                ('coren', models.CharField(max_length=20, verbose_name='COREN')),
                ('coren_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF do COREN')),
                ('cbo', models.CharField(max_length=6, verbose_name='Código Brasileiro de Ocupações (CBO)')),
                ('categoria', models.CharField(choices=[('ENF', 'Enfermeiro'), ('TEC', 'Técnico de Enfermagem'), ('AUX', 'Auxiliar de Enfermagem')], max_length=3, verbose_name='Categoria Profissional')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnes', models.CharField(max_length=7, verbose_name='CNES do Estabelecimento')),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
