# Generated by Django 6.0 on 2026-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeiro',
            name='cns',
            field=models.CharField(error_messages={'unique': 'Já existe um paciente cadastrado com este CNS.'}, max_length=18, unique=True, verbose_name='Cartão Nacional de Saúde (CNS)'),
        ),
        migrations.AlterField(
            model_name='enfermeiro',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Já existe um paciente cadastrado com este CPF.'}, max_length=14, null=True, unique=True),
        ),
    ]
