# Generated by Django 6.0 on 2026-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeiro',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
