# Generated by Django 6.0 on 2026-01-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeiros', '0002_alter_enfermeiro_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeiro',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
