# Generated by Django 6.0 on 2026-01-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermeiros', '0003_alter_enfermeiro_cpf'),
        ('pacientes', '0004_alter_paciente_cep_alter_paciente_cns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aguardando_triagem', 'Aguardando Triagem'), ('em_triagem', 'Em Triagem'), ('triado', 'Triado'), ('finalizado', 'Finalizado')], default='aguardando_triagem', max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeiros.enfermeiro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['data_hora_chegada'],
            },
        ),
    ]
