# Generated by Django 6.0 on 2026-01-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermeiros', '0003_alter_enfermeiro_cpf'),
        ('recepcao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(verbose_name='Queixa Principal')),
                ('inicio_sintomas', models.CharField(blank=True, max_length=100, verbose_name='Início dos Sintomas')),
                ('pressao_arterial', models.CharField(help_text='Ex: 120/80', max_length=7, verbose_name='Pressão Arterial (mmHg)')),
                ('frequencia_cardiaca', models.PositiveIntegerField(verbose_name='Frequência Cardíaca (bpm)')),
                ('frequencia_respiratoria', models.PositiveIntegerField(verbose_name='Frequência Respiratória (irpm)')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura (°C)')),
                ('saturacao_oxigenio', models.PositiveIntegerField(verbose_name='Saturação de O₂ (%)')),
                ('dor', models.PositiveIntegerField(help_text='0 = sem dor | 10 = pior dor possível', verbose_name='Escala de Dor (0 a 10)')),
                ('nivel_consciencia', models.CharField(blank=True, max_length=50, verbose_name='Nível de Consciência')),
                ('mobilidade', models.CharField(blank=True, max_length=50, verbose_name='Mobilidade')),
                ('sangramento', models.BooleanField(default=False, verbose_name='Presença de Sangramento')),
                ('dispneia', models.BooleanField(default=False, verbose_name='Dispneia')),
                ('dor_toracica', models.BooleanField(default=False, verbose_name='Dor Torácica')),
                ('nausea_vomito', models.BooleanField(default=False, verbose_name='Náusea/Vômito')),
                ('classificacao_risco', models.CharField(choices=[('vermelho', 'Vermelho - Emergência'), ('laranja', 'Laranja - Muito Urgente'), ('amarelo', 'Amarelo - Urgente'), ('verde', 'Verde - Pouco Urgente'), ('azul', 'Azul - Não Urgente')], max_length=10, verbose_name='Classificação de Risco')),
                ('conduta', models.TextField(blank=True, verbose_name='Conduta/Encaminhamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_hora_triagem', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Triagem')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem', to='recepcao.atendimento', verbose_name='Atendimento')),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagens', to='enfermeiros.enfermeiro', verbose_name='Enfermeiro Responsável')),
            ],
            options={
                'verbose_name': 'Triagem',
                'verbose_name_plural': 'Triagens',
                'ordering': ['-data_hora_triagem'],
            },
        ),
    ]
