# Generated by Django 6.0 on 2026-01-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermeiros', '0003_alter_enfermeiro_cpf'),
        ('pacientes', '0004_alter_paciente_cep_alter_paciente_cns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Atendimento'), ('em_atendimento', 'Em Atendimento'), ('concluida', 'Concluída')], default='aguardando', max_length=20)),
                ('pressao_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('saturacao_oxigenio', models.IntegerField(blank=True, null=True)),
                ('queixa_principal', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enfermeiros.enfermeiro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
