# Generated by Django 6.0 on 2026-01-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='prioridade',
            field=models.CharField(choices=[('vermelho', 'Vermelho (emergência)'), ('amarelo', 'Amarelo (alta)'), ('verde', 'Verde (média)'), ('azul', 'Azul (baixa)')], default='verde', max_length=10),
        ),
    ]
