# Generated by Django 6.0 on 2026-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_triagem_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Triagem'), ('em_atendimento', 'Em Atendimento (Triagem)'), ('aguardando_medico', 'Aguardando Médico'), ('concluida', 'Concluída')], default='aguardando', max_length=20),
        ),
    ]
